# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_patrols_from_combined_params = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_patrols_from_combined_params",  # 🧪
)  # 🧪

get_patrol_observations_from_patrols_df_and_combined_params = (
    create_func_magicmock(  # 🧪
        anchor="ecoscope.platform.tasks.io",  # 🧪
        func_name="get_patrol_observations_from_patrols_df_and_combined_params",  # 🧪
    )
)  # 🧪
from ecoscope.platform.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)

get_event_type_display_names_from_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_event_type_display_names_from_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.config import get_bounding_box as get_bounding_box
from ecoscope.platform.tasks.config import (
    get_filter_point_coords as get_filter_point_coords,
)
from ecoscope.platform.tasks.config import get_segment_filter as get_segment_filter
from ecoscope.platform.tasks.config import set_traj_filters as set_traj_filters
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)

get_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import (
    set_encounter_rate_metrics as set_encounter_rate_metrics,
)
from ecoscope.platform.tasks.config import (
    get_chart_mode_category_column as get_chart_mode_category_column,
)
from ecoscope.platform.tasks.config import (
    get_chart_mode_spatial_groupers as get_chart_mode_spatial_groupers,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_trend_chart_mode as set_trend_chart_mode
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)

get_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    draw_time_series_bar_chart as draw_time_series_bar_chart,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    concat_dataframes as concat_dataframes,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    decompose_datetime as decompose_datetime,
)
from ecoscope.platform.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    er_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("er_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            truncate_to_time_range=True,
            patrols_overlap_daterange=True,
            include_null_geometry=False,
            sub_page_size=100,
            **(params.get("er_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(combined_params=er_params, **(params.get("prefetch_patrols") or {}))
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_params,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    patrol_events = (
        task(unpack_events_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_params,
            **(params.get("patrol_events") or {}),
        )
        .call()
    )

    event_display_names = (
        task(get_event_type_display_names_from_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("event_display_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            events_gdf=patrol_events,
            append_category_names="duplicates",
            **(params.get("event_display_names") or {}),
        )
        .call()
    )

    patrol_filters = (
        task(set_traj_filters)
        .validate()
        .set_task_instance_id("patrol_filters")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_filters") or {}))
        .call()
    )

    bounding_box = (
        task(get_bounding_box)
        .validate()
        .set_task_instance_id("bounding_box")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("bounding_box") or {}))
        .call()
    )

    filter_point_coords = (
        task(get_filter_point_coords)
        .validate()
        .set_task_instance_id("filter_point_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("filter_point_coords") or {}))
        .call()
    )

    segment_filter = (
        task(get_segment_filter)
        .validate()
        .set_task_instance_id("segment_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("segment_filter") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    spatial_group_ids = (
        task(extract_spatial_grouper_feature_group_names)
        .validate()
        .set_task_instance_id("spatial_group_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=groupers, **(params.get("spatial_group_ids") or {}))
        .call()
    )

    fetch_spatial_groups = (
        task(get_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("fetch_spatial_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client_name, **(params.get("fetch_spatial_groups") or {}))
        .map(argnames=["spatial_features_group_name"], argvalues=spatial_group_ids)
    )

    resolved_groupers = (
        task(resolve_spatial_feature_groups_for_spatial_groupers)
        .validate()
        .set_task_instance_id("resolved_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=groupers,
            spatial_feature_groups=fetch_spatial_groups,
            **(params.get("resolved_groupers") or {}),
        )
        .call()
    )

    set_chart_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_chart_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Patrol Trend", **(params.get("set_chart_title") or {}))
        .call()
    )

    summary_metrics = (
        task(set_encounter_rate_metrics)
        .validate()
        .set_task_instance_id("summary_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("summary_metrics") or {}))
        .call()
    )

    chart_mode = (
        task(set_trend_chart_mode)
        .validate()
        .set_task_instance_id("chart_mode")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("chart_mode") or {}))
        .call()
    )

    time_interval = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("time_interval")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_interval") or {}))
        .call()
    )

    barmode = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("barmode")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("barmode") or {}))
        .call()
    )

    breakdown_category = (
        task(get_chart_mode_category_column)
        .validate()
        .set_task_instance_id("breakdown_category")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(mode=chart_mode, **(params.get("breakdown_category") or {}))
        .call()
    )

    breakdown_spatial_groupers = (
        task(get_chart_mode_spatial_groupers)
        .validate()
        .set_task_instance_id("breakdown_spatial_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(mode=chart_mode, **(params.get("breakdown_spatial_groupers") or {}))
        .call()
    )

    breakdown_group_ids = (
        task(extract_spatial_grouper_feature_group_names)
        .validate()
        .set_task_instance_id("breakdown_group_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=breakdown_spatial_groupers,
            **(params.get("breakdown_group_ids") or {}),
        )
        .call()
    )

    fetch_breakdown_groups = (
        task(get_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("fetch_breakdown_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client_name, **(params.get("fetch_breakdown_groups") or {}))
        .map(argnames=["spatial_features_group_name"], argvalues=breakdown_group_ids)
    )

    resolved_breakdown_groupers = (
        task(resolve_spatial_feature_groups_for_spatial_groupers)
        .validate()
        .set_task_instance_id("resolved_breakdown_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=breakdown_spatial_groupers,
            spatial_feature_groups=fetch_breakdown_groups,
            **(params.get("resolved_breakdown_groupers") or {}),
        )
        .call()
    )

    convert_obs_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_obs_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_obs_tz") or {}),
        )
        .call()
    )

    drop_prefix_obs = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_prefix_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_obs_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_prefix_obs") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_prefix_obs,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            **(params.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_patrol_obs,
            trajectory_segment_filter=segment_filter,
            **(params.get("patrol_traj") or {}),
        )
        .call()
    )

    drop_prefix_traj = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_prefix_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_prefix_traj") or {}),
        )
        .call()
    )

    traj_rename_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_prefix_traj,
            drop_columns=["patrol_type"],
            retain_columns=[],
            rename_columns={"patrol_type__value": "patrol_type"},
            raise_if_not_found=False,
            **(params.get("traj_rename_cols") or {}),
        )
        .call()
    )

    traj_with_date = (
        task(decompose_datetime)
        .validate()
        .set_task_instance_id("traj_with_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            datetime_column="segment_start",
            components=["date"],
            remove_source=False,
            column_prefix=None,
            **(params.get("traj_with_date") or {}),
        )
        .call()
    )

    traj_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_with_date,
            time_col="segment_start",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_temporal_index") or {}),
        )
        .call()
    )

    traj_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("traj_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=traj_temporal_index,
            groupers=resolved_groupers,
            **(params.get("traj_spatial_index") or {}),
        )
        .call()
    )

    traj_breakdown_spatial = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("traj_breakdown_spatial")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=traj_spatial_index,
            groupers=resolved_breakdown_groupers,
            **(params.get("traj_breakdown_spatial") or {}),
        )
        .call()
    )

    traj_rename_time = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_breakdown_spatial,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"segment_start": "trend_time"},
            raise_if_not_found=True,
            **(params.get("traj_rename_time") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_display_names,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    drop_prefix_events = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_prefix_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_prefix_events") or {}),
        )
        .call()
    )

    filter_patrol_events = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_prefix_events,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params.get("filter_patrol_events") or {}),
        )
        .call()
    )

    events_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("events_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_patrol_events,
            time_col="time",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("events_temporal_index") or {}),
        )
        .call()
    )

    events_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("events_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=events_temporal_index,
            groupers=resolved_groupers,
            **(params.get("events_spatial_index") or {}),
        )
        .call()
    )

    events_breakdown_spatial = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("events_breakdown_spatial")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=events_spatial_index,
            groupers=resolved_breakdown_groupers,
            **(params.get("events_breakdown_spatial") or {}),
        )
        .call()
    )

    events_rename_time = (
        task(map_columns)
        .validate()
        .set_task_instance_id("events_rename_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_breakdown_spatial,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"time": "trend_time"},
            raise_if_not_found=True,
            **(params.get("events_rename_time") or {}),
        )
        .call()
    )

    combined_df = (
        task(concat_dataframes)
        .validate()
        .set_task_instance_id("combined_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            dfs=[traj_rename_time, events_rename_time],
            ensure_columns=[
                "event_type",
                "event_type_display",
                "patrol_id",
                "dist_meters",
                "timespan_seconds",
                "segment_start_date",
                "patrol_subject",
                "patrol_type",
                "patrol_serial_number",
                "trend_time",
            ],
            reset_index=False,
            **(params.get("combined_df") or {}),
        )
        .call()
    )

    combined_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("combined_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=combined_df,
            columns=["patrol_serial_number", "patrol_type", "patrol_subject"],
            **(params.get("combined_to_string") or {}),
        )
        .call()
    )

    split_combined = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_combined")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=combined_to_string,
            groupers=resolved_groupers,
            **(params.get("split_combined") or {}),
        )
        .call()
    )

    trend_chart = (
        task(draw_time_series_bar_chart)
        .validate()
        .set_task_instance_id("trend_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="trend_time",
            time_interval=time_interval,
            barmode=barmode,
            y_axis=None,
            agg_function=None,
            category=breakdown_category,
            summary_params=summary_metrics,
            palette=[
                "#FF9600",
                "#F23B0E",
                "#A100CB",
                "#F04564",
                "#03421A",
                "#3089FF",
                "#E26FFF",
                "#8C1700",
                "#002960",
                "#FFD000",
                "#B62879",
                "#680078",
                "#005A56",
                "#0056C7",
                "#331878",
                "#E76826",
            ],
            color_column=None,
            plot_style=None,
            layout_style=None,
            widget_id=set_chart_title,
            **(params.get("trend_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_combined)
    )

    trend_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("trend_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="trend_chart",
            **(params.get("trend_chart_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=trend_chart)
    )

    trend_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("trend_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_chart_title, **(params.get("trend_chart_widget") or {}))
        .map(argnames=["view", "data"], argvalues=trend_chart_html)
    )

    trend_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("trend_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=trend_chart_widget, **(params.get("trend_widget_merged") or {})
        )
        .call()
    )

    trend_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("trend_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[trend_widget_merged],
            groupers=resolved_groupers,
            time_range=time_range,
            **(params.get("trend_dashboard") or {}),
        )
        .call()
    )

    return trend_dashboard
